
const C=window.MISSION_CONFIG,S=window.supabase.createClient(C.supabaseUrl,C.supabaseKey),$=x=>document.getElementById(x);
let D={settings:{},days:[],members:[],program:[],subs:[],todos:[],assign:[],programAssign:[],media:[],templates:[]},date="2026-08-29",mine="",mineDate="",teamFilter="Alle",templateFilter="Alle",session=null,editing=null,galleryItems=[],galleryIndex=0;
const esc=(s="")=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const tval=t=>(t||"").slice(0,5), fmt=d=>new Date(d+"T12:00").toLocaleDateString("de-DE",{weekday:"long",day:"2-digit",month:"long"});
function err(m){$("error").textContent=m;$("error").classList.remove("hidden")}function clearErr(){$("error").classList.add("hidden")}
function toggleTheme(){let x=document.documentElement.dataset.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=x;localStorage.setItem("gyV10Theme",x)}document.documentElement.dataset.theme=localStorage.getItem("gyV10Theme")||"dark";
async function load(){
 clearErr();try{
  let qs=await Promise.all([
   S.from("app_settings").select("*").limit(1),S.from("festival_days").select("*").order("event_date"),
   S.from("team_members").select("*").order("name"),S.from("program_items").select("*").order("event_date").order("start_time"),
   S.from("program_subitems").select("*").order("sort_order"),S.from("content_todos").select("*").order("sort_order"),
   S.from("todo_assignments").select("*"),S.from("program_assignments").select("*"),S.from("todo_media").select("*").order("sort_order"),
   S.from("templates").select("*").order("created_at")
  ]);qs.forEach(q=>{if(q.error)throw q.error});
  [D.settings,D.days,D.members,D.program,D.subs,D.todos,D.assign,D.programAssign,D.media,D.templates]=[qs[0].data[0]||{},qs[1].data,qs[2].data,qs[3].data,qs[4].data,qs[5].data,qs[6].data,qs[7].data,qs[8].data,qs[9].data];
  if(D.days.length&&!D.days.some(x=>x.event_date===date))date=D.days[0].event_date;if(!mineDate)mineDate=date;render()
 }catch(e){console.error(e);err("Supabase: "+e.message)}
}
function render(){header();days("days",date,"selectDate");dayHero();progress("progress",date);dayparts("dayparts",date,false);mineUI();team();templates();if(session)adminUI()}
function header(){$("title").textContent=D.settings.event_title||"Sommerfestival 2026";$("subtitle").textContent=D.settings.event_subtitle||"Heaven Now";$("ig").href=D.settings.instagram_url||"#";$("tt").href=D.settings.tiktok_url||"#"}
function showView(v){document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));$("view-"+v).classList.add("active");document.querySelectorAll("[data-view]").forEach(x=>x.classList.toggle("active",x.dataset.view===v));if(v==="mine")mineUI()}
function days(id,selected,fn){$(id).innerHTML=D.days.map(d=>`<button class="day ${d.event_date===selected?"active":""}" onclick="${fn}('${d.event_date}')"><strong>${esc(d.short_label||fmt(d.event_date).slice(0,2))}</strong><small>${esc(d.display_date||fmt(d.event_date).replace(/^[^,]+, /,""))}</small></button>`).join("")}
function selectDate(x){date=x;render()}function selectAdminDate(x){date=x;render()}function selectMineDate(x){mineDate=x;mineUI()}
function dayObj(d){return D.days.find(x=>x.event_date===d)||{event_date:d,theme:"",description:""}}
function dayHero(){let d=dayObj(date);$("dayHero").innerHTML=`<div class="dateLine">${fmt(date)}</div><h2>${esc(d.theme||"Tagesplan")}</h2>${d.description?`<p>${esc(d.description)}</p>`:""}`}
function todoCat(x){return x.type||"Story"}function dayTodos(d){return D.todos.filter(x=>x.event_date===d)}
function progress(id,d){let a=dayTodos(d),cats=["Story","Reel","Foto","Interview"];$(id).innerHTML=`<div class="progressGrid">${cats.map(c=>{let z=a.filter(x=>x.type===c),done=z.filter(x=>x.done).length;return `<div class="metric"><div class="metricTop"><span>${c}${c==="Story"?"s":c==="Foto"?"s":""}</span><strong>${done} / ${z.length}</strong></div><div class="bar"><i style="width:${z.length?done/z.length*100:0}%"></i></div></div>`}).join("")}</div>`}
function programRoles(p){let rows=D.programAssign.filter(a=>a.program_id===p.id), groups={};rows.forEach(a=>{(groups[a.role]??=[]).push(memberName(a.member_id))});return Object.entries(groups).filter(([,n])=>n.length).map(([r,n])=>`<span class="role">${esc(r)} · <strong>${n.map(esc).join(" + ")}</strong></span>`).join("")}
function memberName(id){return D.members.find(m=>m.id===id)?.name||"?"}
function todoAssignees(id){return D.assign.filter(a=>a.todo_id===id).map(a=>memberName(a.member_id))}
function mediaFor(id){return D.media.filter(m=>m.todo_id===id)}
function embed(url){if(!url)return"";try{let u=new URL(url);if(u.hostname.includes("tiktok.com")){let m=u.pathname.match(/\/video\/(\d+)/);if(m)return `<div class="videoBox"><iframe loading="lazy" allow="fullscreen; autoplay" src="https://www.tiktok.com/player/v1/${m[1]}?autoplay=0"></iframe></div>`}if(u.hostname.includes("instagram.com")){let clean=url.split("?")[0].replace(/\/?$/,"/");return `<div class="videoBox"><iframe loading="lazy" src="${esc(clean)}embed/"></iframe></div>`}}catch(e){}return""}
function todoHTML(x,admin=false){let people=todoAssignees(x.id),med=mediaFor(x.id),images=med.filter(m=>m.media_type==="image"),vid=med.find(m=>m.media_type==="video"||m.media_type==="link");return `<div class="todo ${x.done?"todoDone":""}"><div class="todoTop"><div><div class="todoTitle">${esc(x.type)} · ${esc(x.title)}</div><div class="todoMeta">${x.due_time?esc(tval(x.due_time))+" · ":""}${esc(x.description||"")}</div></div>${x.done?`<span>✓</span>`:""}</div>${people.length?`<div class="assignees">${people.map(n=>`<span class="person">${esc(n)}</span>`).join("")}</div>`:""}${x.example_url?embed(x.example_url)+`<a class="external" target="_blank" href="${esc(x.example_url)}">Original öffnen ↗</a>`:""}${vid&&vid.url&&!x.example_url?embed(vid.url):""}${images.length?`<div class="mediaStrip">${images.map((m,i)=>`<div class="thumb" onclick="openTodoGallery('${x.id}',${i})"><img src="${esc(m.url)}"><small>${esc(m.caption||"")}</small></div>`).join("")}</div>`:""}${admin?`<div class="editRow"><button class="checkBtn ${x.done?"done":""}" onclick="toggleTodo('${x.id}',${!x.done})">${x.done?"Erledigt ✓":"Als erledigt markieren"}</button><button class="editBtn" onclick="openForm('todo','${x.id}')">Bearbeiten</button><button class="deleteBtn" onclick="removeRow('todo','${x.id}')">Löschen</button></div>`:""}</div>`}
function subHTML(s,idx,admin=false){let ts=D.todos.filter(t=>t.subitem_id===s.id).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0));return `<div class="sub"><div class="subHead"><div class="num">${idx+1}</div><div><h4>${esc(s.title)}</h4><div class="subMeta">${[s.kind,tval(s.start_time)].filter(Boolean).map(esc).join(" · ")}</div>${s.description?`<p style="margin:5px 0">${esc(s.description)}</p>`:""}</div></div><div class="todos">${ts.map(t=>todoHTML(t,admin)).join("")}</div>${admin?`<div class="editRow"><button class="addBtn" onclick="openForm('todo',null,'${s.id}')">+ Story / Reel / Foto / Interview</button><button class="editBtn" onclick="openForm('sub','${s.id}')">Unterpunkt bearbeiten</button><button class="deleteBtn" onclick="removeRow('sub','${s.id}')">Löschen</button></div>`:""}</div>`}
function programHTML(p,admin=false){let ss=D.subs.filter(s=>s.program_id===p.id).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0));return `<article class="program"><div class="programTop"><div class="programTime">${esc(tval(p.start_time))}</div><div><h3>${esc(p.title)}</h3>${p.speaker?`<div class="speaker">Sprecher: ${esc(p.speaker)}</div>`:""}${p.description?`<p class="programDesc">${esc(p.description)}</p>`:""}<div class="roles">${programRoles(p)}</div></div></div><div class="sublist">${ss.map((s,i)=>subHTML(s,i,admin)).join("")}</div>${admin?`<div class="editRow"><button class="addBtn" onclick="openForm('sub',null,null,'${p.id}')">+ Unterpunkt</button><button class="editBtn" onclick="openForm('program','${p.id}')">Programmpunkt bearbeiten</button><button class="editBtn" onclick="openForm('proles','${p.id}')">Zuweisungen</button><button class="deleteBtn" onclick="removeRow('program','${p.id}')">Löschen</button></div>`:""}</article>`}
function dayparts(id,d,admin){let labels={morning:D.settings.heading_morning||"Morgen",midday:D.settings.heading_midday||"Mittag",evening:D.settings.heading_evening||"Abend"};$(id).innerHTML=Object.entries(labels).map(([k,l])=>{let ps=D.program.filter(p=>p.event_date===d&&p.daypart===k);return `<section class="daypart"><div class="daypartHead"><h2>${esc(l)}</h2>${admin?`<button class="addBtn" onclick="openForm('program',null,null,null,'${k}')">+ Programmpunkt</button>`:""}</div><div class="programList">${ps.length?ps.map(p=>programHTML(p,admin)).join(""):`<p>Noch keine Programmpunkte.</p>`}</div></section>`}).join("")}
function mineUI(){let sel=$("minePerson");sel.innerHTML=`<option value="">Person auswählen …</option>${D.members.map(m=>`<option value="${m.id}" ${mine===m.id?"selected":""}>${esc(m.name)}</option>`).join("")}`;days("mineDays",mineDate,"selectMineDate");let all=mine?assignmentsFor(mine):[],today=all.filter(x=>x.date===mineDate);$("calendarAll").classList.toggle("hidden",!mine);let next=all.find(x=>new Date(x.date+"T"+(x.time||"23:59"))>=new Date());$("mineNext").innerHTML=next?`<div class="nextCard"><div class="kicker" style="color:inherit;opacity:.6">Nächster Einsatz</div><h3 style="margin-top:5px">${fmt(next.date)} · ${esc(next.time)}</h3><p>${esc(next.title)} · ${esc(next.role)}</p></div>`:"";$("mineList").innerHTML=mine?(today.length?today.map(x=>`<div class="mineItem"><strong>${esc(x.time)}</strong><div><strong>${esc(x.title)}</strong><p>${esc(x.role)}${x.sub?" · "+esc(x.sub):""}</p></div></div>`).join(""):`<p>Keine Einsätze an diesem Tag.</p>`):`<p>Wähle zuerst deinen Namen aus.</p>`}
function setMinePerson(x){mine=x;mineUI()}
function assignmentsFor(mid){let out=[];D.programAssign.filter(a=>a.member_id===mid).forEach(a=>{let p=D.program.find(x=>x.id===a.program_id);if(p)out.push({date:p.event_date,time:tval(p.start_time),title:p.title,role:a.role})});D.assign.filter(a=>a.member_id===mid).forEach(a=>{let t=D.todos.find(x=>x.id===a.todo_id),s=t&&D.subs.find(x=>x.id===t.subitem_id),p=s&&D.program.find(x=>x.id===s.program_id);if(t&&p)out.push({date:t.event_date,time:tval(t.due_time)||tval(p.start_time),title:t.title,role:t.type,sub:s.title})});return out.sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time))}
function exportMine(){let a=assignmentsFor(mine),ics="BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//Gospel Youth//V10//DE\n";a.forEach(x=>{let d=x.date.replaceAll("-",""),s=(x.time||"12:00").replace(":","")+"00";ics+=`BEGIN:VEVENT\nDTSTART:${d}T${s}\nSUMMARY:${x.title}\nDESCRIPTION:${x.role}${x.sub?" - "+x.sub:""}\nEND:VEVENT\n`});ics+="END:VCALENDAR";blob(ics,(memberName(mine)||"Einsaetze")+".ics","text/calendar")}
function blob(t,n,type){let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([t],{type}));a.download=n;a.click()}
function team(){let roles=["Alle",...new Set(D.members.flatMap(m=>m.roles||[]))];$("teamFilters").innerHTML=roles.map(r=>`<button class="pill ${teamFilter===r?"active":""}" onclick="teamFilter=${JSON.stringify(r)};team()">${esc(r)}</button>`).join("");let a=D.members.filter(m=>teamFilter==="Alle"||(m.roles||[]).includes(teamFilter));$("teamGrid").innerHTML=a.map(m=>`<div class="teamCard"><h3>${esc(m.name)}</h3><p>${(m.roles||[]).map(esc).join(" · ")}</p><div class="actions">${m.phone?`<a href="tel:${esc(m.phone)}">Anrufen</a><a target="_blank" href="https://wa.me/${esc(m.phone.replace(/\D/g,""))}">WhatsApp</a>`:""}${m.email?`<a href="mailto:${esc(m.email)}">E-Mail</a>`:""}</div></div>`).join("")}
function templates(){let cats=["Alle",...new Set(D.templates.map(x=>x.category).filter(Boolean))];$("templateFilters").innerHTML=cats.map(r=>`<button class="pill ${templateFilter===r?"active":""}" onclick="templateFilter=${JSON.stringify(r)};templates()">${esc(r)}</button>`).join("");let a=D.templates.filter(x=>templateFilter==="Alle"||x.category===templateFilter);$("templateGrid").innerHTML=a.map((x,i)=>`<div class="templateCard"><img src="${esc(x.file_url)}" onclick="openTemplateGallery('${x.id}')"><div class="templateBody"><strong>${esc(x.title)}</strong><p>${esc(x.category||"Vorlage")}${x.description?" · "+esc(x.description):""}</p></div></div>`).join("")}
function openTodoGallery(id,i=0){galleryItems=mediaFor(id).filter(x=>x.media_type==="image");galleryIndex=i;showGallery()}function openTemplateGallery(id){let x=D.templates.find(t=>t.id===id);galleryItems=x?[{url:x.file_url,caption:x.description||x.title}]:[];galleryIndex=0;showGallery()}function showGallery(){if(!galleryItems.length)return;let x=galleryItems[galleryIndex];$("galleryImg").src=x.url;$("galleryCaption").textContent=x.caption||"";$("gallery").classList.remove("hidden")}function galleryStep(n){galleryIndex=(galleryIndex+n+galleryItems.length)%galleryItems.length;showGallery()}function closeGallery(){$("gallery").classList.add("hidden")}
async function openAdmin(){$("admin").classList.remove("hidden");let {data}=await S.auth.getSession();session=data.session;adminRender()}function closeAdmin(){$("admin").classList.add("hidden")}async function login(){let {data,error}=await S.auth.signInWithPassword({email:$("email").value.trim(),password:$("password").value});if(error){$("loginMsg").textContent=error.message;return}session=data.session;adminRender()}async function logout(){await S.auth.signOut();session=null;adminRender()}
function adminRender(){$("login").classList.toggle("hidden",!!session);$("adminApp").classList.toggle("hidden",!session);if(session){$("adminEmail").textContent=session.user.email;adminUI()}}
function adminUI(){days("adminDays",date,"selectAdminDate");let d=dayObj(date);$("adminDayTitle").textContent=fmt(date)+" · "+(d.theme||"Tagesplan");progress("adminProgress",date);dayparts("adminDayparts",date,true);$("adminTemplates").innerHTML=D.templates.map(x=>`<div class="templateCard"><img src="${esc(x.file_url)}"><div class="templateBody"><strong>${esc(x.title)}</strong><div class="editRow"><button class="editBtn" onclick="openForm('template','${x.id}')">Bearbeiten</button><button class="deleteBtn" onclick="removeRow('template','${x.id}')">Löschen</button></div></div></div>`).join("");$("adminTeam").innerHTML=D.members.map(m=>`<div class="teamCard"><h3>${esc(m.name)}</h3><p>${(m.roles||[]).map(esc).join(" · ")}</p><div class="editRow"><button class="editBtn" onclick="openForm('member','${m.id}')">Bearbeiten</button><button class="deleteBtn" onclick="removeRow('member','${m.id}')">Löschen</button></div></div>`).join("")}
function editDay(){openForm("day",date)}
function optionsMembers(sel=[]){return D.members.map(m=>`<label style="display:flex;gap:8px;align-items:center"><input type="checkbox" class="memberCheck" value="${m.id}" ${sel.includes(m.id)?"checked":""}> ${esc(m.name)}</label>`).join("")}
function optionsProgram(sel=""){return D.program.filter(p=>p.event_date===date).map(p=>`<option value="${p.id}" ${p.id===sel?"selected":""}>${esc(tval(p.start_time))} · ${esc(p.title)}</option>`).join("")}
function openForm(type,id=null,subId=null,programId=null,daypart=null){editing={type,id,subId,programId,daypart};let x=null,h="";if(type==="day"){x=dayObj(id);h=`<div class="formGrid"><div class="field"><label>Thema des Tages</label><input id="fTheme" value="${esc(x.theme)}"></div><div class="field"><label>Beschreibung</label><textarea id="fDesc">${esc(x.description||"")}</textarea></div><div class="field"><label>Kurzes Label</label><input id="fShort" value="${esc(x.short_label||"")}"></div><div class="field"><label>Datumsanzeige</label><input id="fDisplay" value="${esc(x.display_date||"")}"></div></div>`}
if(type==="program"){x=D.program.find(a=>a.id===id);h=`<div class="formGrid two"><div class="field"><label>Uhrzeit</label><input id="fTime" type="time" value="${tval(x?.start_time)||"10:00"}"></div><div class="field"><label>Tageszeit</label><select id="fPart">${["morning","midday","evening"].map(v=>`<option value="${v}" ${(x?.daypart||daypart)===v?"selected":""}>${v==="morning"?"Morgen":v==="midday"?"Mittag":"Abend"}</option>`).join("")}</select></div><div class="field full"><label>Titel</label><input id="fTitle" value="${esc(x?.title)}"></div><div class="field"><label>Sprecher</label><input id="fSpeaker" value="${esc(x?.speaker)}"></div><div class="field full"><label>Beschreibung</label><textarea id="fDesc">${esc(x?.description)}</textarea></div></div>`}
if(type==="sub"){x=D.subs.find(a=>a.id===id);h=`<div class="formGrid two"><div class="field full"><label>Programmpunkt</label><select id="fProgram">${optionsProgram(x?.program_id||programId)}</select></div><div class="field"><label>Art</label><select id="fKind">${["Worship","Predigt","Games","Gebet","Kleingruppe","Freizeit","Sonstiges"].map(v=>`<option ${x?.kind===v?"selected":""}>${v}</option>`).join("")}</select></div><div class="field"><label>Reihenfolge</label><input id="fOrder" type="number" value="${x?.sort_order||1}"></div><div class="field"><label>Uhrzeit optional</label><input id="fTime" type="time" value="${tval(x?.start_time)}"></div><div class="field full"><label>Titel</label><input id="fTitle" value="${esc(x?.title)}"></div><div class="field full"><label>Beschreibung</label><textarea id="fDesc">${esc(x?.description)}</textarea></div></div>`}
if(type==="todo"){x=D.todos.find(a=>a.id===id);let ass=x?D.assign.filter(a=>a.todo_id===x.id).map(a=>a.member_id):[];h=`<div class="formGrid two"><div class="field"><label>Typ</label><select id="fType">${["Story","Reel","Foto","Interview"].map(v=>`<option ${x?.type===v?"selected":""}>${v}</option>`).join("")}</select></div><div class="field"><label>Reihenfolge</label><input id="fOrder" type="number" value="${x?.sort_order||1}"></div><div class="field full"><label>Titel</label><input id="fTitle" value="${esc(x?.title)}"></div><div class="field full"><label>Beschreibung / Shotlist</label><textarea id="fDesc">${esc(x?.description)}</textarea></div><div class="field"><label>Deadline / Uhrzeit</label><input id="fTime" type="time" value="${tval(x?.due_time)}"></div><div class="field full"><label>TikTok-/Instagram-Beispiel-Link</label><input id="fURL" value="${esc(x?.example_url)}"><div class="help">TikTok-Videos werden direkt als Player angezeigt, wenn der Beitrag Embedding erlaubt.</div></div><div class="field full"><label>Mehrere Verantwortliche</label><div>${optionsMembers(ass)}</div></div><div class="field full"><label>Beispielbilder / eigene MP4-Datei</label><input id="fFiles" type="file" accept="image/png,image/jpeg,image/webp,video/mp4" multiple><div class="help">Mehrere Bilder möglich. MP4 wird direkt im Browser abgespielt.</div></div><div class="field full"><label>Beschreibungen zu Uploads</label><textarea id="fCaptions" placeholder="Eine Zeile pro Datei"></textarea></div></div>`}
if(type==="proles"){let cur=D.programAssign.filter(a=>a.program_id===id),roles=["Fotograf","Story-Koordinator","Story-Maker","Reel-Maker","Interview"];h=`<div class="formGrid">${roles.map(r=>`<div class="field"><label>${r} – mehrere möglich</label><div data-role="${r}" class="roleChecks">${optionsMembers(cur.filter(a=>a.role===r).map(a=>a.member_id))}</div></div>`).join("")}</div>`}
if(type==="member"){x=D.members.find(a=>a.id===id);h=`<div class="formGrid"><div class="field"><label>Name</label><input id="fName" value="${esc(x?.name)}"></div><div class="field"><label>E-Mail</label><input id="fEmail" type="email" value="${esc(x?.email)}"></div><div class="field"><label>Telefon</label><input id="fPhone" value="${esc(x?.phone)}"></div><div class="field"><label>Rollen, Komma getrennt</label><input id="fRoles" value="${esc((x?.roles||[]).join(", "))}"></div></div>`}
if(type==="template"){x=D.templates.find(a=>a.id===id);h=`<div class="formGrid"><div class="field"><label>Titel</label><input id="fTitle" value="${esc(x?.title)}"></div><div class="field"><label>Kategorie</label><select id="fCategory">${["Story","Post","Reel Cover","Speaker","Verse","Sonstiges"].map(v=>`<option ${x?.category===v?"selected":""}>${v}</option>`).join("")}</select></div><div class="field"><label>Beschreibung</label><textarea id="fDesc">${esc(x?.description)}</textarea></div><div class="field"><label>PNG/JPG</label><input id="fFiles" type="file" accept="image/png,image/jpeg,image/webp"></div></div>`}
$("formTitle").textContent=id?"Bearbeiten":"Neu hinzufügen";$("formBody").innerHTML=h;$("formError").classList.add("hidden");$("formModal").classList.remove("hidden")}
function closeForm(){$("formModal").classList.add("hidden");editing=null}const val=id=>$(id)?.value||"";
async function upload(file,folder){let path=`${folder}/${Date.now()}-${Math.random().toString(36).slice(2)}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`,r=await S.storage.from(C.storageBucket).upload(path,file);if(r.error)throw r.error;return S.storage.from(C.storageBucket).getPublicUrl(path).data.publicUrl}
async function saveForm(){let {type,id,subId}=editing,b=$("save");b.disabled=true;try{
 if(type==="day"){let r=await S.from("festival_days").update({theme:val("fTheme"),description:val("fDesc"),short_label:val("fShort"),display_date:val("fDisplay")}).eq("event_date",id);if(r.error)throw r.error}
 if(type==="program"){let row={event_date:date,start_time:val("fTime"),daypart:val("fPart"),title:val("fTitle")||"Programmpunkt",speaker:val("fSpeaker")||null,description:val("fDesc"),published:true},r=id?await S.from("program_items").update(row).eq("id",id):await S.from("program_items").insert(row);if(r.error)throw r.error}
 if(type==="sub"){let row={program_id:val("fProgram"),kind:val("fKind"),sort_order:+val("fOrder")||1,start_time:val("fTime")||null,title:val("fTitle")||"Unterpunkt",description:val("fDesc")},r=id?await S.from("program_subitems").update(row).eq("id",id):await S.from("program_subitems").insert(row);if(r.error)throw r.error}
 if(type==="todo"){let sid=id?D.todos.find(x=>x.id===id)?.subitem_id:subId, row={subitem_id:sid,event_date:date,type:val("fType"),title:val("fTitle")||val("fType"),description:val("fDesc"),due_time:val("fTime")||null,example_url:val("fURL")||null,sort_order:+val("fOrder")||1};let tid=id;if(id){let r=await S.from("content_todos").update(row).eq("id",id);if(r.error)throw r.error}else{let r=await S.from("content_todos").insert(row).select("id").single();if(r.error)throw r.error;tid=r.data.id}await S.from("todo_assignments").delete().eq("todo_id",tid);let mids=[...document.querySelectorAll(".memberCheck:checked")].map(x=>x.value);if(mids.length){let r=await S.from("todo_assignments").insert(mids.map(member_id=>({todo_id:tid,member_id})));if(r.error)throw r.error}let files=[...$("fFiles").files],caps=val("fCaptions").split("\n");for(let i=0;i<files.length;i++){let url=await upload(files[i],"todo-media/"+tid),r=await S.from("todo_media").insert({todo_id:tid,media_type:files[i].type.startsWith("video")?"video":"image",url,caption:(caps[i]||"").trim(),sort_order:i+1});if(r.error)throw r.error}}
 if(type==="proles"){await S.from("program_assignments").delete().eq("program_id",id);let rows=[];document.querySelectorAll(".roleChecks").forEach(box=>box.querySelectorAll("input:checked").forEach(ch=>rows.push({program_id:id,member_id:ch.value,role:box.dataset.role})));if(rows.length){let r=await S.from("program_assignments").insert(rows);if(r.error)throw r.error}}
 if(type==="member"){let row={name:val("fName")||"Person",email:val("fEmail")||null,phone:val("fPhone")||null,roles:val("fRoles").split(",").map(x=>x.trim()).filter(Boolean)},r=id?await S.from("team_members").update(row).eq("id",id):await S.from("team_members").insert(row);if(r.error)throw r.error}
 if(type==="template"){let old=D.templates.find(x=>x.id===id),url=old?.file_url||null,file=$("fFiles").files[0];if(file)url=await upload(file,"templates");if(!url)throw Error("Bitte ein Bild auswählen.");let row={title:val("fTitle")||"Vorlage",category:val("fCategory"),description:val("fDesc"),file_url:url},r=id?await S.from("templates").update(row).eq("id",id):await S.from("templates").insert(row);if(r.error)throw r.error}
 closeForm();await load()
}catch(e){$("formError").textContent=e.message;$("formError").classList.remove("hidden");console.error(e)}finally{b.disabled=false}}
async function toggleTodo(id,done){let r=await S.from("content_todos").update({done}).eq("id",id);if(r.error)return alert(r.error.message);await load()}
async function removeRow(type,id){if(!confirm("Wirklich löschen?"))return;let table={program:"program_items",sub:"program_subitems",todo:"content_todos",member:"team_members",template:"templates"}[type],r=await S.from(table).delete().eq("id",id);if(r.error)return alert(r.error.message);await load()}
S.auth.onAuthStateChange((_e,s)=>{session=s;if(!$("admin").classList.contains("hidden"))adminRender()});document.addEventListener("DOMContentLoaded",load);
